### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by rvndnishad** [Ardumed/applianceControl_webapp#5]
Hi Himanshu,
I was checking your appliance store app, received below issue from the Heroku server: 
"Application error
An error occurred in the application and your page could not be served. If you are the application owner, check your logs for details."

thanks

**Comment by himanshusingh2407** [comment]
Hi Arvind,
Thanks for reporting the issue. Actually I am using free instance of Heroku. So, it is not up all the time. This can be the reason why it gave that error. Currently it's working fine.

**Comment by rvndnishad** [comment]
oh, okay! Thanks buddy!!!
